name: Publish to GH Pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Jupyter
        run: pip install notebook

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate HTML
        run: |
          jupyter nbconvert --execute --to html --output-dir dist notebook.ipynb
          mv dist/notebook.html dist/index.html

      - name: Publish to GH Pages
        uses: jamesives/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
